sudo: false
language: node_js
node_js:
  - "4"
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp test/config/scanner.travis.yml test/config/scanner.yml
  - cp test/config/cc-scanner.travis.yml test/config/cc-scanner.yml
  - cp test/config/service.travis.yml test/config/service.yml
env:
  - TEST_SUITE=lint
  - TEST_SUITE=test
script: "npm run-script $TEST_SUITE"
