chromanode:
  network: testnet
  enableHTTPS: false
  host: localhost
  port: 3001
  enableNotifications: true

logger:
  level: verbose # verbose, info, warning, error
  filename: service.log

postgresql:
  url: postgres://user:pass@host:port/database_name
  poolSize: 20
